## 1. Importing Required Libraries

In [ ]:
import pandas as pd 
import numpy as np

## 2. Loading the first Dataset

In [132]:
product = pd.read_csv("products_2024.csv")

## 3. Displaying the First Few Records of the Dataset

In [133]:
product.head()

,product_upc,product_name,brand,department_name,category_name,size,unit,vendor_name,vendor_phone,regular_price,unit_cost,pack_size
0,4.332180e+11,Rainshadow Produce Apples,Rainshadow Produce,Produce,Apples,1 lb,lb,Evergreen Organics,206-555-0110,3.11,2.31,1
1,3.863790e+11,Evergreen Farms Bananas,Evergreen Farms,Produce,Bananas,1 lb,lb,Frontier Foods Wholesale,206-555-0118,5.33,3.68,1
2,1.615590e+11,Evergreen Farms Kale,Evergreen Farms,Produce,Kale,3 lb,lb,Pacific Produce Co.,206-555-0111,1.76,1.10,1
3,9.310340e+11,Rainshadow Produce Spinach,Rainshadow Produce,Produce,Spinach,3 lb,lb,Bulk Barn West,206-555-0115,1.15,0.84,6
4,5.341930e+11,North Fork Organics Carrots,North Fork Organics,Produce,Carrots,2 lb,lb,Bulk Barn West,206-555-0115,4.52,3.19,6

## Understanding Dataset Structure and Data Types

In [ ]:
product.info()

## Checking Duplicate Records

In [ ]:
product.duplicated()

In [ ]:
product['product_upc'].duplicated()

In [ ]:
product['product_name'].duplicated()

## Checking Missing Values

In [1]:
product.isnull()

NameError: name 'product' is not defined

## Checking Unique Values Column

In [134]:
product['brand'].unique()

<StringArray>
[ 'Rainshadow Produce',     'Evergreen Farms', 'North Fork Organics',
       'Skyline Dairy',   'Cascadia Creamery',           'EverFresh',
     'Blue Sky Bakery',        'Stone Hearth',        'Grain & Glow',
          'Sun Valley',      'Frontier Foods',           'VitaCrest',
           'WellNorth',        'Sunrise Labs',       'Sack & Barrel',
        'Everton Bulk',          'Daily Deli',      'Hearth & Ladle',
    'Greenway Kitchen',        'Meadow Meats',         'Ocean Crest']
Length: 21, dtype: str

In [ ]:
product['category_name'].unique()

In [ ]:
product['vendor_name'].unique()

In [ ]:
product['product_name'].nunique()

In [ ]:
product['brand'].nunique()

## Analyzing Distribution

In [ ]:
product['vendor_name'].value_counts()

In [ ]:

product['product_name'].value_counts()

In [ ]:
product['brand'].value_counts()

## Creating Brand ID Mapping

In [135]:
map_brand =  {
    'Rainshadow Produce' : 1,
    'Evergreen Farms' : 2,
    'North Fork Organics' : 3,
    'Skyline Dairy' : 4,
    'Cascadia Creamery' : 5,
    'EverFresh' : 6,
    'Blue Sky Bakery' : 7,
    'Stone Hearth' : 8,
    'Grain & Glow' : 9,
    'Sun Valley' : 10,
    'Frontier Foods' : 11,
    'VitaCrest' : 12,
    'WellNorth' : 13,
    'Sunrise Labs' : 14,
    'Sack & Barrel' : 15,
    'Everton Bulk' : 16,
    'Daily Deli' : 17,
    'Hearth & Ladle' : 18,
    'Greenway Kitchen' : 19,
    'Meadow Meats' : 20,
    'Ocean Crest' : 21
}

In [ ]:
product["brand_ID"] = product["brand"].map(map_brand)

## Creating Vendor ID Mapping

In [ ]:
map_vendor = {
    'Evergreen Organics' : 1,
    'Pacific Produce Co.' : 2,
    'Frontier Foods Wholesale' : 3,
    'Cascadia Dairy' : 4,
    'Sunrise Wellness' : 5,
    'Meadow Meats' : 6,
    'Ocean Crest Seafood' : 7,
    'Blue Sky Bakery' : 8,
    'Bulk Barn West' : 9
}

In [ ]:
product['vendor_ID'] = product['vendor_name'].map(map_vendor)

## Creating department ID Mapping

In [ ]:
map_department = {
    'Produce' : 1,
    'Dairy' : 2,
    'Bakery' : 3,
    'Grocery' : 4,
    'Wellness' : 5, 
    'Deli' : 6,
    'Meat/Seafood' : 7,
    'Bulk' : 8
}

In [ ]:
product['department_ID'] = product['department_name'].map(map_department)

## Creating Category Table with Unique Category IDs

In [137]:
category_df = product[['category_name']].drop_duplicates().reset_index(drop=True)

category_df['category_ID'] = range(
    1,
    len(category_df) + 1
)

In [138]:
product = product.merge(
    category_df, 
    on='category_name',
    how='left'
)

## Displaying the First Few Records of the Dataset

In [139]:
product.head()

,product_upc,product_name,brand,department_name,category_name,size,unit,vendor_name,vendor_phone,regular_price,unit_cost,pack_size,category_ID
0,4.332180e+11,Rainshadow Produce Apples,Rainshadow Produce,Produce,Apples,1 lb,lb,Evergreen Organics,206-555-0110,3.11,2.31,1,1
1,3.863790e+11,Evergreen Farms Bananas,Evergreen Farms,Produce,Bananas,1 lb,lb,Frontier Foods Wholesale,206-555-0118,5.33,3.68,1,2
2,1.615590e+11,Evergreen Farms Kale,Evergreen Farms,Produce,Kale,3 lb,lb,Pacific Produce Co.,206-555-0111,1.76,1.10,1,3
3,9.310340e+11,Rainshadow Produce Spinach,Rainshadow Produce,Produce,Spinach,3 lb,lb,Bulk Barn West,206-555-0115,1.15,0.84,6,4
4,5.341930e+11,North Fork Organics Carrots,North Fork Organics,Produce,Carrots,2 lb,lb,Bulk Barn West,206-555-0115,4.52,3.19,6,5

## Analyzing Unique Product Distribution by Department and Category

In [156]:
product.groupby([ 'department_name','category_name','product_name']).nunique()

                                                                      product_upc  \
department_name category_name      product_name
Bakery          Bagels             Blue Sky Bakery Bagels                       1
                Blueberry Muffins  Grain & Glow Blueberry Muffins               1
                Croissant          Stone Hearth Croissant                       1
                Sourdough Loaf     Blue Sky Bakery Sourdough Loaf               1
                Whole Wheat Bread  Stone Hearth Whole Wheat Bread               1
Bulk            Almonds Raw        Sack & Barrel Almonds Raw                    1
                Brown Rice         Everton Bulk Brown Rice                      1
                Cashews            Everton Bulk Cashews                         1
                Coffee Beans       Sack & Barrel Coffee Beans                   1
                Pistachios         Everton Bulk Pistachios                      1
                Trail Mix          Everton Bulk Trail Mix                       1
                Walnuts            Sack & Barrel Walnuts                        1
Dairy           Almond Milk        Cascadia Creamery Almond Milk                1
                Butter Unsalted    Cascadia Creamery Butter Unsalted            1
                Cheddar Cheese     Cascadia Creamery Cheddar Cheese             1
                Cottage Cheese     EverFresh Cottage Cheese                     1
                Cream              Skyline Dairy Cream                          1
                Eggs               EverFresh Eggs                               1
                Greek Yogurt       Cascadia Creamery Greek Yogurt               1
                Milk 2%            Skyline Dairy Milk 2%                        1
                Sour Cream         EverFresh Sour Cream                         1
                Whole Milk         Cascadia Creamery Whole Milk                 1
Deli            Hummus             Daily Deli Hummus                            1
                Pasta Salad        Daily Deli Pasta Salad                       1
                Potato Salad       Daily Deli Potato Salad                      1
                Roast Chicken      Hearth & Ladle Roast Chicken                 1
                Tomato Soup        Greenway Kitchen Tomato Soup                 1
Grocery         Basmati Rice       Sun Valley Basmati Rice                      1
                Black Beans        Sun Valley Black Beans                       1
                Cereal             Frontier Foods Cereal                        1
                Chickpeas          Sun Valley Chickpeas                         1
                Honey              Frontier Foods Honey                         1
                Olive Oil          Frontier Foods Olive Oil                     1
                Peanut Butter      Frontier Foods Peanut Butter                 1
                Quinoa             Sun Valley Quinoa                            1
                Rolled Oats        Sun Valley Rolled Oats                       1
                Spaghetti          Sun Valley Spaghetti                         1
                Tomato Sauce       Sun Valley Tomato Sauce                      1
                Tortillas          Sun Valley Tortillas                         1
Meat/Seafood    Chicken Breast     Meadow Meats Chicken Breast                  1
                Ground Beef        Ocean Crest Ground Beef                      1
                Pork Chops         Ocean Crest Pork Chops                       1
                Salmon Fillet      Meadow Meats Salmon Fillet                   1
                Shrimp 16-20       Ocean Crest Shrimp 16-20                     1
Produce         Apples             Rainshadow Produce Apples                    1
                Avocados           Rainshadow Produce Avocados                  1
                Bananas            Evergreen Farms Bananas                      1
                Blueberries        Rainshadow Produce Blueberries               1
                Broccoli           Evergreen Farms Broccoli                     1
                Carrots            North Fork Organics Carrots                  1
                Kale               Evergreen Farms Kale                         1
                Potatoes           Rainshadow Produce Potatoes                  1
                Spinach            Rainshadow Produce Spinach                   1
                Strawberries       Rainshadow Produce Strawberries              1
Wellness        Electrolyte Powder Sunrise Labs Electrolyte Powder              1
                Fish Oil           WellNorth Fish Oil                           1
                Magnesium          Sunrise Labs Magnesium                       1
                Multivitamin       VitaCrest Multivitamin                       1
                Probiotic          WellNorth Probiotic                          1
                Vitamin D3         VitaCrest Vitamin D3                         1

                                                                      brand  \
department_name category_name      product_name
Bakery          Bagels             Blue Sky Bakery Bagels                 1
                Blueberry Muffins  Grain & Glow Blueberry Muffins         1
                Croissant          Stone Hearth Croissant                 1
                Sourdough Loaf     Blue Sky Bakery Sourdough Loaf         1
                Whole Wheat Bread  Stone Hearth Whole Wheat Bread         1
Bulk            Almonds Raw        Sack & Barrel Almonds Raw              1
                Brown Rice         Everton Bulk Brown Rice                1
                Cashews            Everton Bulk Cashews                   1
                Coffee Beans       Sack & Barrel Coffee Beans             1
                Pistachios         Everton Bulk Pistachios                1
                Trail Mix          Everton Bulk Trail Mix                 1
                Walnuts            Sack & Barrel Walnuts                  1
Dairy           Almond Milk        Cascadia Creamery Almond Milk          1
                Butter Unsalted    Cascadia Creamery Butter Unsalted      1
                Cheddar Cheese     Cascadia Creamery Cheddar Cheese       1
                Cottage Cheese     EverFresh Cottage Cheese               1
                Cream              Skyline Dairy Cream                    1
                Eggs               EverFresh Eggs                         1
                Greek Yogurt       Cascadia Creamery Greek Yogurt         1
                Milk 2%            Skyline Dairy Milk 2%                  1
                Sour Cream         EverFresh Sour Cream                   1
                Whole Milk         Cascadia Creamery Whole Milk           1
Deli            Hummus             Daily Deli Hummus                      1
                Pasta Salad        Daily Deli Pasta Salad                 1
                Potato Salad       Daily Deli Potato Salad                1
                Roast Chicken      Hearth & Ladle Roast Chicken           1
                Tomato Soup        Greenway Kitchen Tomato Soup           1
Grocery         Basmati Rice       Sun Valley Basmati Rice                1
                Black Beans        Sun Valley Black Beans                 1
                Cereal             Frontier Foods Cereal                  1
                Chickpeas          Sun Valley Chickpeas                   1
                Honey              Frontier Foods Honey                   1
                Olive Oil          Frontier Foods Olive Oil               1
                Peanut Butter      Frontier Foods Peanut Butter           1
                Quinoa             Sun Valley Quinoa                      1
                Rolled Oats        Sun Valley Rolled Oats                 1
                Spaghetti          Sun Valley Spaghetti                   1
                Tomato Sauce       Sun Valley Tomato Sauce                1
                Tortillas          Sun Valley Tortillas                   1
Meat/Seafood    Chicken Breast     Meadow Meats Chicken Breast            1
                Ground Beef        Ocean Crest Ground Beef                1
                Pork Chops         Ocean Crest Pork Chops                 1
                Salmon Fillet      Meadow Meats Salmon Fillet             1
                Shrimp 16-20       Ocean Crest Shrimp 16-20               1
Produce         Apples             Rainshadow Produce Apples              1
                Avocados           Rainshadow Produce Avocados            1
                Bananas            Evergreen Farms Bananas                1
                Blueberries        Rainshadow Produce Blueberries         1
                Broccoli           Evergreen Farms Broccoli               1
                Carrots            North Fork Organics Carrots            1
                Kale               Evergreen Farms Kale                   1
                Potatoes           Rainshadow Produce Potatoes            1
                Spinach            Rainshadow Produce Spinach             1
                Strawberries       Rainshadow Produce Strawberries        1
Wellness        Electrolyte Powder Sunrise Labs Electrolyte Powder        1
                Fish Oil           WellNorth Fish Oil                     1
                Magnesium          Sunrise Labs Magnesium                 1
                Multivitamin       VitaCrest Multivitamin                 1
                Probiotic          WellNorth Probiotic                    1
                Vitamin D3         VitaCrest Vitamin D3                   1

                                                                      size  \
department_name category_name      product_name
Bakery          Bagels             Blue Sky Bakery Bagels                1
                Blueberry Muffins  Grain & Glow Blueberry Muffins        1
                Croissant          Stone Hearth Croissant                1
                Sourdough Loaf     Blue Sky Bakery Sourdough Loaf        1
                Whole Wheat Bread  Stone Hearth Whole Wheat Bread        1
Bulk            Almonds Raw        Sack & Barrel Almonds Raw             1
                Brown Rice         Everton Bulk Brown Rice               1
                Cashews            Everton Bulk Cashews                  1
                Coffee Beans       Sack & Barrel Coffee Beans            1
                Pistachios         Everton Bulk Pistachios               1
                Trail Mix          Everton Bulk Trail Mix                1
                Walnuts            Sack & Barrel Walnuts                 1
Dairy           Almond Milk        Cascadia Creamery Almond Milk         1
                Butter Unsalted    Cascadia Creamery Butter Unsalted     1
                Cheddar Cheese     Cascadia Creamery Cheddar Cheese      1
                Cottage Cheese     EverFresh Cottage Cheese              1
                Cream              Skyline Dairy Cream                   1
                Eggs               EverFresh Eggs                        1
                Greek Yogurt       Cascadia Creamery Greek Yogurt        1
                Milk 2%            Skyline Dairy Milk 2%                 1
                Sour Cream         EverFresh Sour Cream                  1
                Whole Milk         Cascadia Creamery Whole Milk          1
Deli            Hummus             Daily Deli Hummus                     1
                Pasta Salad        Daily Deli Pasta Salad                1
                Potato Salad       Daily Deli Potato Salad               1
                Roast Chicken      Hearth & Ladle Roast Chicken          1
                Tomato Soup        Greenway Kitchen Tomato Soup          1
Grocery         Basmati Rice       Sun Valley Basmati Rice               1
                Black Beans        Sun Valley Black Beans                1
                Cereal             Frontier Foods Cereal                 1
                Chickpeas          Sun Valley Chickpeas                  1
                Honey              Frontier Foods Honey                  1
                Olive Oil          Frontier Foods Olive Oil              1
                Peanut Butter      Frontier Foods Peanut Butter          1
                Quinoa             Sun Valley Quinoa                     1
                Rolled Oats        Sun Valley Rolled Oats                1
                Spaghetti          Sun Valley Spaghetti                  1
                Tomato Sauce       Sun Valley Tomato Sauce               1
                Tortillas          Sun Valley Tortillas                  1
Meat/Seafood    Chicken Breast     Meadow Meats Chicken Breast           1
                Ground Beef        Ocean Crest Ground Beef               1
                Pork Chops         Ocean Crest Pork Chops                1
                Salmon Fillet      Meadow Meats Salmon Fillet            1
                Shrimp 16-20       Ocean Crest Shrimp 16-20              1
Produce         Apples             Rainshadow Produce Apples             1
                Avocados           Rainshadow Produce Avocados           1
                Bananas            Evergreen Farms Bananas               1
                Blueberries        Rainshadow Produce Blueberries        1
                Broccoli           Evergreen Farms Broccoli              1
                Carrots            North Fork Organics Carrots           1
                Kale               Evergreen Farms Kale                  1
                Potatoes           Rainshadow Produce Potatoes           1
                Spinach            Rainshadow Produce Spinach            1
                Strawberries       Rainshadow Produce Strawberries       1
Wellness        Electrolyte Powder Sunrise Labs Electrolyte Powder       1
                Fish Oil           WellNorth Fish Oil                    1
                Magnesium          Sunrise Labs Magnesium                1
                Multivitamin       VitaCrest Multivitamin                1
                Probiotic          WellNorth Probiotic                   1
                Vitamin D3         VitaCrest Vitamin D3                  1

                                                                      unit  \
department_name category_name      product_name
Bakery          Bagels             Blue Sky Bakery Bagels                1
                Blueberry Muffins  Grain & Glow Blueberry Muffins        1
                Croissant          Stone Hearth Croissant                1
                Sourdough Loaf     Blue Sky Bakery Sourdough Loaf        1
                Whole Wheat Bread  Stone Hearth Whole Wheat Bread        1
Bulk            Almonds Raw        Sack & Barrel Almonds Raw             1
                Brown Rice         Everton Bulk Brown Rice               1
                Cashews            Everton Bulk Cashews                  1
                Coffee Beans       Sack & Barrel Coffee Beans            1
                Pistachios         Everton Bulk Pistachios               1
                Trail Mix          Everton Bulk Trail Mix                1
                Walnuts            Sack & Barrel Walnuts                 1
Dairy           Almond Milk        Cascadia Creamery Almond Milk         1
                Butter Unsalted    Cascadia Creamery Butter Unsalted     1
                Cheddar Cheese     Cascadia Creamery Cheddar Cheese      1
                Cottage Cheese     EverFresh Cottage Cheese              1
                Cream              Skyline Dairy Cream                   1
                Eggs               EverFresh Eggs                        1
                Greek Yogurt       Cascadia Creamery Greek Yogurt        1
                Milk 2%            Skyline Dairy Milk 2%                 1
                Sour Cream         EverFresh Sour Cream                  1
                Whole Milk         Cascadia Creamery Whole Milk          1
Deli            Hummus             Daily Deli Hummus                     1
                Pasta Salad        Daily Deli Pasta Salad                1
                Potato Salad       Daily Deli Potato Salad               1
                Roast Chicken      Hearth & Ladle Roast Chicken          1
                Tomato Soup        Greenway Kitchen Tomato Soup          1
Grocery         Basmati Rice       Sun Valley Basmati Rice               1
                Black Beans        Sun Valley Black Beans                1
                Cereal             Frontier Foods Cereal                 1
                Chickpeas          Sun Valley Chickpeas                  1
                Honey              Frontier Foods Honey                  1
                Olive Oil          Frontier Foods Olive Oil              1
                Peanut Butter      Frontier Foods Peanut Butter          1
                Quinoa             Sun Valley Quinoa                     1
                Rolled Oats        Sun Valley Rolled Oats                1
                Spaghetti          Sun Valley Spaghetti                  1
                Tomato Sauce       Sun Valley Tomato Sauce               1
                Tortillas          Sun Valley Tortillas                  1
Meat/Seafood    Chicken Breast     Meadow Meats Chicken Breast           1
                Ground Beef        Ocean Crest Ground Beef               1
                Pork Chops         Ocean Crest Pork Chops                1
                Salmon Fillet      Meadow Meats Salmon Fillet            1
                Shrimp 16-20       Ocean Crest Shrimp 16-20              1
Produce         Apples             Rainshadow Produce Apples             1
                Avocados           Rainshadow Produce Avocados           1
                Bananas            Evergreen Farms Bananas               1
                Blueberries        Rainshadow Produce Blueberries        1
                Broccoli           Evergreen Farms Broccoli              1
                Carrots            North Fork Organics Carrots           1
                Kale               Evergreen Farms Kale                  1
                Potatoes           Rainshadow Produce Potatoes           1
                Spinach            Rainshadow Produce Spinach            1
                Strawberries       Rainshadow Produce Strawberries       1
Wellness        Electrolyte Powder Sunrise Labs Electrolyte Powder       1
                Fish Oil           WellNorth Fish Oil                    1
                Magnesium          Sunrise Labs Magnesium                1
                Multivitamin       VitaCrest Multivitamin                1
                Probiotic          WellNorth Probiotic                   1
                Vitamin D3         VitaCrest Vitamin D3                  1

                                                                      vendor_name  \
department_name category_name      product_name
Bakery          Bagels             Blue Sky Bakery Bagels                       1
                Blueberry Muffins  Grain & Glow Blueberry Muffins               1
                Croissant          Stone Hearth Croissant                       1
                Sourdough Loaf     Blue Sky Bakery Sourdough Loaf               1
                Whole Wheat Bread  Stone Hearth Whole Wheat Bread               1
Bulk            Almonds Raw        Sack & Barrel Almonds Raw                    1
                Brown Rice         Everton Bulk Brown Rice                      1
                Cashews            Everton Bulk Cashews                         1
                Coffee Beans       Sack & Barrel Coffee Beans                   1
                Pistachios         Everton Bulk Pistachios                      1

## Loading Promotions Dataset

In [157]:
promotions = pd.read_csv('promotions_2024.csv')

## Displaying the First Few Records of the Dataset

In [158]:
promotions.head()

,promo_id,product_upc,promo_type,discount_percent,start_date,end_date,product_name,department_name,brand
0,PR0011832,471349361832,PCT_OFF,15,2024-01-01,2024-01-07,Meadow Meats Salmon Fillet,Meat/Seafood,Meadow Meats
1,PR0019579,831727889579,LOYALTY_PCT,30,2024-01-01,2024-01-07,Sun Valley Tortillas,Grocery,Sun Valley
2,PR0013186,190229413186,LOYALTY_PCT,5,2024-01-01,2024-01-07,Greenway Kitchen Tomato Soup,Deli,Greenway Kitchen
3,PR0011904,452991241904,PCT_OFF,30,2024-01-01,2024-01-07,Sunrise Labs Magnesium,Wellness,Sunrise Labs
4,PR0015433,216073375433,BOGO50,50,2024-01-01,2024-01-07,Sun Valley Basmati Rice,Grocery,Sun Valley

## Understanding Dataset Structure and Data Types

In [159]:
promotions.info()

<class 'pandas.DataFrame'>
RangeIndex: 530 entries, 0 to 529
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   promo_id          530 non-null    str
 1   product_upc       530 non-null    int64
 2   promo_type        530 non-null    str
 3   discount_percent  530 non-null    int64
 4   start_date        530 non-null    str
 5   end_date          530 non-null    str
 6   product_name      530 non-null    str
 7   department_name   530 non-null    str
 8   brand             530 non-null    str
dtypes: int64(2), str(7)
memory usage: 37.4 KB

## Converting Date Columns to Datetime Format

In [ ]:
promotions["sale_datetime"] = pd.to_datetime(promotions["sale_datetime"])

In [160]:
promotions["start_date"] = pd.to_datetime(promotions["start_date"])
promotions["end_date"] = pd.to_datetime(promotions["end_date"])

## Understanding Dataset Structure and Data Types

In [161]:
promotions.info()

<class 'pandas.DataFrame'>
RangeIndex: 530 entries, 0 to 529
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   promo_id          530 non-null    str
 1   product_upc       530 non-null    int64
 2   promo_type        530 non-null    str
 3   discount_percent  530 non-null    int64
 4   start_date        530 non-null    datetime64[us]
 5   end_date          530 non-null    datetime64[us]
 6   product_name      530 non-null    str
 7   department_name   530 non-null    str
 8   brand             530 non-null    str
dtypes: datetime64[us](2), int64(2), str(5)
memory usage: 37.4 KB

## Checking Unique Values Column

In [162]:
promotions["product_upc"].nunique()

12

## Checking Duplicate Records in Promotions Dataset

In [163]:
promotions.duplicated().sum()

np.int64(0)

## Checking Product UPC Consistency Between Datasets

In [164]:
set(promotions["product_upc"]) - set(product["product_upc"])

{190229413186,
 216073375433,
 431351823374,
 433218196001,
 452991241904,
 471349361832,
 586923226025,
 831727889579,
 883561595148,
 931034131647,
 951343320037}

## Loading first sales Dataset

In [165]:
q1_sales = pd.read_csv('sales_2024_q1.csv')

## Understanding Dataset Structure and Data Types

In [166]:
q1_sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 13545 entries, 0 to 13544
Data columns (total 31 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   receipt_id            13545 non-null  str
 1   line_number           13545 non-null  int64
 2   sale_datetime         13545 non-null  str
 3   store_id              13545 non-null  int64
 4   store_name            13545 non-null  str
 5   store_address         13545 non-null  str
 6   store_city            13545 non-null  str
 7   store_state           13545 non-null  str
 8   store_zip             13545 non-null  int64
 9   cashier_name          13545 non-null  str
 10  tender_type           13545 non-null  str
 11  customer_segment      13545 non-null  str
 12  product_upc           13545 non-null  int64
 13  product_name          13545 non-null  str
 14  brand                 13545 non-null  str
 15  department_name       13545 non-null  str
 16  category_name         13545 non-null  str
 17  size                  13545 non-null  str
 18  unit                  13545 non-null  str
 19  vendor_name           13545 non-null  str
 20  vendor_phone          13545 non-null  str
 21  pack_size             13545 non-null  int64
 22  regular_price         13545 non-null  float64
 23  unit_cost             13545 non-null  float64
 24  quantity              13545 non-null  int64
 25  promo_type            1299 non-null   str
 26  promo_id              1299 non-null   str
 27  unit_price_effective  13545 non-null  float64
 28  line_subtotal         13545 non-null  float64
 29  tax_amount            13545 non-null  float64
 30  weekend_flag          13545 non-null  bool
dtypes: bool(1), float64(5), int64(6), str(19)
memory usage: 3.1 MB

## Displaying the First Few Records of the Dataset

In [167]:
q1_sales.head()

,receipt_id,line_number,sale_datetime,store_id,store_name,store_address,store_city,store_state,store_zip,cashier_name,...,pack_size,regular_price,unit_cost,quantity,promo_type,promo_id,unit_price_effective,line_subtotal,tax_amount,weekend_flag
0,101-20240101-0001,1,01/01/2024 14:20,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,Quinn,...,1,5.34,3.24,1,NaN,NaN,5.34,5.34,0.0,False
1,101-20240101-0001,2,01/01/2024 14:20,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,Quinn,...,6,1.15,0.84,1,LOYALTY_PCT,PR0011647,1.09,1.09,0.0,False
2,101-20240101-0001,3,01/01/2024 14:20,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,Quinn,...,6,4.52,3.19,2,NaN,NaN,4.52,9.04,0.0,False
3,101-20240101-0001,4,01/01/2024 14:20,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,Quinn,...,2,1.09,0.79,2,NaN,NaN,1.09,2.18,0.0,False
4,101-20240101-0002,1,01/01/2024 13:30,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,Riley,...,6,16.74,10.94,2,NaN,NaN,16.74,33.48,0.0,False

## Converting Date Columns to Datetime Format

In [168]:
q1_sales["sale_datetime"] = pd.to_datetime(q1_sales["sale_datetime"])

In [169]:
q1_sales["sale_date"] = q1_sales["sale_datetime"].dt.date
q1_sales["sale_time"] = q1_sales["sale_datetime"].dt.time

## Displaying the First Few Records of the Dataset

In [170]:
q1_sales.head()

,receipt_id,line_number,sale_datetime,store_id,store_name,store_address,store_city,store_state,store_zip,cashier_name,...,unit_cost,quantity,promo_type,promo_id,unit_price_effective,line_subtotal,tax_amount,weekend_flag,sale_date,sale_time
0,101-20240101-0001,1,2024-01-01 14:20:00,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,Quinn,...,3.24,1,NaN,NaN,5.34,5.34,0.0,False,2024-01-01,14:20:00
1,101-20240101-0001,2,2024-01-01 14:20:00,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,Quinn,...,0.84,1,LOYALTY_PCT,PR0011647,1.09,1.09,0.0,False,2024-01-01,14:20:00
2,101-20240101-0001,3,2024-01-01 14:20:00,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,Quinn,...,3.19,2,NaN,NaN,4.52,9.04,0.0,False,2024-01-01,14:20:00
3,101-20240101-0001,4,2024-01-01 14:20:00,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,Quinn,...,0.79,2,NaN,NaN,1.09,2.18,0.0,False,2024-01-01,14:20:00
4,101-20240101-0002,1,2024-01-01 13:30:00,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,Riley,...,10.94,2,NaN,NaN,16.74,33.48,0.0,False,2024-01-01,13:30:00

checking empty values for recipt_id

In [171]:
q1_sales.duplicated().sum()

np.int64(0)

checking null

In [172]:
q1_sales.isnull().sum()

receipt_id                  0
line_number                 0
sale_datetime               0
store_id                    0
store_name                  0
store_address               0
store_city                  0
store_state                 0
store_zip                   0
cashier_name                0
tender_type                 0
customer_segment            0
product_upc                 0
product_name                0
brand                       0
department_name             0
category_name               0
size                        0
unit                        0
vendor_name                 0
vendor_phone                0
pack_size                   0
regular_price               0
unit_cost                   0
quantity                    0
promo_type              12246
promo_id                12246
unit_price_effective        0
line_subtotal               0
tax_amount                  0
weekend_flag                0
sale_date                   0
sale_time                   0
dtype: int64

In [173]:
q1_sales['promo_type'].isnull().sum()

q1_sales['promo_type'].info()

q1_sales['promo_type'].head(20)

<class 'pandas.Series'>
RangeIndex: 13545 entries, 0 to 13544
Series name: promo_type
Non-Null Count  Dtype
--------------  -----
1299 non-null   str
dtypes: str(1)
memory usage: 105.9 KB

0             NaN
1     LOYALTY_PCT
2             NaN
3             NaN
4             NaN
5         PCT_OFF
6             NaN
7             NaN
8             NaN
9             NaN
10            NaN
11            NaN
12            NaN
13            NaN
14            NaN
15        PCT_OFF
16            NaN
17            NaN
18            NaN
19            NaN
Name: promo_type, dtype: str

Checking for column promotype

In [174]:
q1_sales['promo_id'].isnull().sum()
q1_sales['promo_id'].unique()

<StringArray>
[        nan, 'PR0011647', 'PR0016978', 'PR0016001', 'PR0019579', 'PR0016025',
 'PR0015433', 'PR0011904', 'PR0011832', 'PR0013374',
 ...
 'PR0853186', 'PR0859579', 'PR0856978', 'PR0855433', 'PR0856025', 'PR0851832',
 'PR0851904', 'PR0850037', 'PR0856001', 'PR0853374']
Length: 126, dtype: str

checking for q2 sales file

In [175]:
q2_sales = pd.read_csv('sales_2024_q2.csv')

In [176]:
q2_sales["line_number"].head()

0    1
1    2
2    3
3    4
4    5
Name: line_number, dtype: int64

getting information

In [177]:
q2_sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 13479 entries, 0 to 13478
Data columns (total 31 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   receipt_id            13479 non-null  str
 1   line_number           13479 non-null  int64
 2   sale_datetime         13479 non-null  str
 3   store_id              13479 non-null  int64
 4   store_name            13479 non-null  str
 5   store_address         13479 non-null  str
 6   store_city            13479 non-null  str
 7   store_state           13479 non-null  str
 8   store_zip             13479 non-null  int64
 9   cashier_name          13479 non-null  str
 10  tender_type           13479 non-null  str
 11  customer_segment      13479 non-null  str
 12  product_upc           13479 non-null  int64
 13  product_name          13479 non-null  str
 14  brand                 13479 non-null  str
 15  department_name       13479 non-null  str
 16  category_name         13479 non-null  str
 17  size                  13479 non-null  str
 18  unit                  13479 non-null  str
 19  vendor_name           13479 non-null  str
 20  vendor_phone          13479 non-null  str
 21  pack_size             13479 non-null  int64
 22  regular_price         13479 non-null  float64
 23  unit_cost             13479 non-null  float64
 24  quantity              13479 non-null  int64
 25  promo_type            1282 non-null   str
 26  promo_id              1282 non-null   str
 27  unit_price_effective  13479 non-null  float64
 28  line_subtotal         13479 non-null  float64
 29  tax_amount            13479 non-null  float64
 30  weekend_flag          13479 non-null  bool
dtypes: bool(1), float64(5), int64(6), str(19)
memory usage: 3.1 MB

Converting q2 sales datetieme dtype string to datetime formate

In [178]:
q2_sales.head()

,receipt_id,line_number,sale_datetime,store_id,store_name,store_address,store_city,store_state,store_zip,cashier_name,...,pack_size,regular_price,unit_cost,quantity,promo_type,promo_id,unit_price_effective,line_subtotal,tax_amount,weekend_flag
0,101-20240401-0001,1,2024-04-01 11:23,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,Taylor,...,1,2.79,1.89,1,NaN,NaN,2.79,2.79,0.0,False
1,101-20240401-0001,2,2024-04-01 11:23,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,Taylor,...,1,3.11,2.31,1,NaN,NaN,3.11,3.11,0.0,False
2,101-20240401-0001,3,2024-04-01 11:23,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,Taylor,...,2,19.41,13.90,1,LOYALTY_PCT,PR0926025,14.56,14.56,0.0,False
3,101-20240401-0001,4,2024-04-01 11:23,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,Taylor,...,6,1.15,0.84,1,LOYALTY_PCT,PR0921647,0.98,0.98,0.0,False
4,101-20240401-0001,5,2024-04-01 11:23,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,Taylor,...,1,5.44,3.40,2,NaN,NaN,5.44,10.88,0.0,False

In [179]:
q2_sales["sale_datetime"] = pd.to_datetime(q2_sales["sale_datetime"])

In [180]:
q2_sales["sale_time"] = q2_sales["sale_datetime"].dt.time
q2_sales["sale_date"] = q2_sales["sale_datetime"].dt.date

In [181]:
q2_sales.head()

,receipt_id,line_number,sale_datetime,store_id,store_name,store_address,store_city,store_state,store_zip,cashier_name,...,unit_cost,quantity,promo_type,promo_id,unit_price_effective,line_subtotal,tax_amount,weekend_flag,sale_time,sale_date
0,101-20240401-0001,1,2024-04-01 11:23:00,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,Taylor,...,1.89,1,NaN,NaN,2.79,2.79,0.0,False,11:23:00,2024-04-01
1,101-20240401-0001,2,2024-04-01 11:23:00,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,Taylor,...,2.31,1,NaN,NaN,3.11,3.11,0.0,False,11:23:00,2024-04-01
2,101-20240401-0001,3,2024-04-01 11:23:00,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,Taylor,...,13.90,1,LOYALTY_PCT,PR0926025,14.56,14.56,0.0,False,11:23:00,2024-04-01
3,101-20240401-0001,4,2024-04-01 11:23:00,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,Taylor,...,0.84,1,LOYALTY_PCT,PR0921647,0.98,0.98,0.0,False,11:23:00,2024-04-01
4,101-20240401-0001,5,2024-04-01 11:23:00,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,Taylor,...,3.40,2,NaN,NaN,5.44,10.88,0.0,False,11:23:00,2024-04-01

checking null value

In [182]:
q2_sales.isnull().sum()

receipt_id                  0
line_number                 0
sale_datetime               0
store_id                    0
store_name                  0
store_address               0
store_city                  0
store_state                 0
store_zip                   0
cashier_name                0
tender_type                 0
customer_segment            0
product_upc                 0
product_name                0
brand                       0
department_name             0
category_name               0
size                        0
unit                        0
vendor_name                 0
vendor_phone                0
pack_size                   0
regular_price               0
unit_cost                   0
quantity                    0
promo_type              12197
promo_id                12197
unit_price_effective        0
line_subtotal               0
tax_amount                  0
weekend_flag                0
sale_time                   0
sale_date                   0
dtype: int64

cheking 3 file

In [183]:
q3_sales = pd.read_csv("sales_2024_q3.csv")

In [184]:
q3_sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 13097 entries, 0 to 13096
Data columns (total 31 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   receipt_id            13097 non-null  str
 1   line_number           13097 non-null  int64
 2   sale_datetime         13097 non-null  str
 3   store_id              13097 non-null  int64
 4   store_name            13097 non-null  str
 5   store_address         13097 non-null  str
 6   store_city            13097 non-null  str
 7   store_state           13097 non-null  str
 8   store_zip             13097 non-null  int64
 9   cashier_name          13097 non-null  str
 10  tender_type           13097 non-null  str
 11  customer_segment      13097 non-null  str
 12  product_upc           13097 non-null  int64
 13  product_name          13097 non-null  str
 14  brand                 13097 non-null  str
 15  department_name       13097 non-null  str
 16  category_name         13097 non-null  str
 17  size                  13097 non-null  str
 18  unit                  13097 non-null  str
 19  vendor_name           13097 non-null  str
 20  vendor_phone          13097 non-null  str
 21  pack_size             13097 non-null  int64
 22  regular_price         13097 non-null  float64
 23  unit_cost             13097 non-null  float64
 24  quantity              13097 non-null  int64
 25  promo_type            1390 non-null   str
 26  promo_id              1390 non-null   str
 27  unit_price_effective  13097 non-null  float64
 28  line_subtotal         13097 non-null  float64
 29  tax_amount            13097 non-null  float64
 30  weekend_flag          13097 non-null  bool
dtypes: bool(1), float64(5), int64(6), str(19)
memory usage: 3.0 MB

Converting q3 sales datetime dtype string to datetime formate

In [185]:
q3_sales["sale_datetime"] = pd.to_datetime(q3_sales["sale_datetime"])

In [186]:
q3_sales["sale_date"] = q3_sales["sale_datetime"].dt.date
q3_sales["sale_time"] = q3_sales["sale_datetime"].dt.time

In [187]:
q3_sales.head()

,receipt_id,line_number,sale_datetime,store_id,store_name,store_address,store_city,store_state,store_zip,cashier_name,...,unit_cost,quantity,promo_type,promo_id,unit_price_effective,line_subtotal,tax_amount,weekend_flag,sale_date,sale_time
0,101-20240701-0001,1,2024-07-01 08:45:00,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,Casey,...,5.36,1,NaN,NaN,8.37,8.37,0.0,False,2024-07-01,08:45:00
1,101-20240701-0001,2,2024-07-01 08:45:00,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,Casey,...,1.20,1,PCT_OFF,PR1835148,1.39,1.39,0.0,False,2024-07-01,08:45:00
2,101-20240701-0001,3,2024-07-01 08:45:00,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,Casey,...,10.94,1,NaN,NaN,16.74,16.74,0.0,False,2024-07-01,08:45:00
3,101-20240701-0001,4,2024-07-01 08:45:00,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,Casey,...,1.20,2,PCT_OFF,PR1835148,1.39,2.78,0.0,False,2024-07-01,08:45:00
4,101-20240701-0001,5,2024-07-01 08:45:00,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,Casey,...,0.84,1,NaN,NaN,1.15,1.15,0.0,False,2024-07-01,08:45:00

Inserting file 4

In [188]:
q4_sales = pd.read_csv("sales_2024_q4.csv")

In [189]:
q4_sales.head()

,receipt_id,line_number,sale_datetime,store_id,store_name,store_address,store_city,store_state,store_zip,cashier_name,...,pack_size,regular_price,unit_cost,quantity,promo_type,promo_id,unit_price_effective,line_subtotal,tax_amount,weekend_flag
0,101-20241001-0001,1,10/01/24 12:25 PM,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,Taylor,...,4,2.68,1.82,2,NaN,NaN,2.68,5.36,0.0,False
1,101-20241001-0002,1,10/01/24 12:37 PM,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,Riley,...,1,5.95,3.76,1,NaN,NaN,5.95,5.95,0.0,False
2,101-20241001-0002,2,10/01/24 12:37 PM,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,Riley,...,1,15.66,9.86,2,NaN,NaN,15.66,31.32,0.0,False
3,101-20241001-0002,3,10/01/24 12:37 PM,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,Riley,...,2,0.92,0.69,1,NaN,NaN,0.92,0.92,0.0,False
4,101-20241001-0002,4,10/01/24 12:37 PM,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,Riley,...,4,5.47,3.40,1,NaN,NaN,5.47,5.47,0.0,False

In [190]:
q4_sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 13165 entries, 0 to 13164
Data columns (total 31 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   receipt_id            13165 non-null  str
 1   line_number           13165 non-null  int64
 2   sale_datetime         13165 non-null  str
 3   store_id              13165 non-null  int64
 4   store_name            13165 non-null  str
 5   store_address         13165 non-null  str
 6   store_city            13165 non-null  str
 7   store_state           13165 non-null  str
 8   store_zip             13165 non-null  int64
 9   cashier_name          13165 non-null  str
 10  tender_type           13165 non-null  str
 11  customer_segment      13165 non-null  str
 12  product_upc           13165 non-null  int64
 13  product_name          13165 non-null  str
 14  brand                 13165 non-null  str
 15  department_name       13165 non-null  str
 16  category_name         13165 non-null  str
 17  size                  13165 non-null  str
 18  unit                  13165 non-null  str
 19  vendor_name           13165 non-null  str
 20  vendor_phone          13165 non-null  str
 21  pack_size             13165 non-null  int64
 22  regular_price         13165 non-null  float64
 23  unit_cost             13165 non-null  float64
 24  quantity              13165 non-null  int64
 25  promo_type            1324 non-null   str
 26  promo_id              1324 non-null   str
 27  unit_price_effective  13165 non-null  float64
 28  line_subtotal         13165 non-null  float64
 29  tax_amount            13165 non-null  float64
 30  weekend_flag          13165 non-null  bool
dtypes: bool(1), float64(5), int64(6), str(19)
memory usage: 3.0 MB

Converting sales date time string to datetime format

In [191]:
q4_sales.head()

,receipt_id,line_number,sale_datetime,store_id,store_name,store_address,store_city,store_state,store_zip,cashier_name,...,pack_size,regular_price,unit_cost,quantity,promo_type,promo_id,unit_price_effective,line_subtotal,tax_amount,weekend_flag
0,101-20241001-0001,1,10/01/24 12:25 PM,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,Taylor,...,4,2.68,1.82,2,NaN,NaN,2.68,5.36,0.0,False
1,101-20241001-0002,1,10/01/24 12:37 PM,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,Riley,...,1,5.95,3.76,1,NaN,NaN,5.95,5.95,0.0,False
2,101-20241001-0002,2,10/01/24 12:37 PM,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,Riley,...,1,15.66,9.86,2,NaN,NaN,15.66,31.32,0.0,False
3,101-20241001-0002,3,10/01/24 12:37 PM,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,Riley,...,2,0.92,0.69,1,NaN,NaN,0.92,0.92,0.0,False
4,101-20241001-0002,4,10/01/24 12:37 PM,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,Riley,...,4,5.47,3.40,1,NaN,NaN,5.47,5.47,0.0,False

In [192]:
q4_sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 13165 entries, 0 to 13164
Data columns (total 31 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   receipt_id            13165 non-null  str
 1   line_number           13165 non-null  int64
 2   sale_datetime         13165 non-null  str
 3   store_id              13165 non-null  int64
 4   store_name            13165 non-null  str
 5   store_address         13165 non-null  str
 6   store_city            13165 non-null  str
 7   store_state           13165 non-null  str
 8   store_zip             13165 non-null  int64
 9   cashier_name          13165 non-null  str
 10  tender_type           13165 non-null  str
 11  customer_segment      13165 non-null  str
 12  product_upc           13165 non-null  int64
 13  product_name          13165 non-null  str
 14  brand                 13165 non-null  str
 15  department_name       13165 non-null  str
 16  category_name         13165 non-null  str
 17  size                  13165 non-null  str
 18  unit                  13165 non-null  str
 19  vendor_name           13165 non-null  str
 20  vendor_phone          13165 non-null  str
 21  pack_size             13165 non-null  int64
 22  regular_price         13165 non-null  float64
 23  unit_cost             13165 non-null  float64
 24  quantity              13165 non-null  int64
 25  promo_type            1324 non-null   str
 26  promo_id              1324 non-null   str
 27  unit_price_effective  13165 non-null  float64
 28  line_subtotal         13165 non-null  float64
 29  tax_amount            13165 non-null  float64
 30  weekend_flag          13165 non-null  bool
dtypes: bool(1), float64(5), int64(6), str(19)
memory usage: 3.0 MB

In [193]:
q4_sales["sale_datetime"] = pd.to_datetime(q4_sales["sale_datetime"], format = "%m/%d/%y %I:%M %p")

In [194]:
q4_sales["sale_time"] = q4_sales["sale_datetime"].dt.time

In [195]:
q4_sales["sale_date"] = q4_sales["sale_datetime"].dt.date

In [196]:
q4_sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 13165 entries, 0 to 13164
Data columns (total 33 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   receipt_id            13165 non-null  str
 1   line_number           13165 non-null  int64
 2   sale_datetime         13165 non-null  datetime64[us]
 3   store_id              13165 non-null  int64
 4   store_name            13165 non-null  str
 5   store_address         13165 non-null  str
 6   store_city            13165 non-null  str
 7   store_state           13165 non-null  str
 8   store_zip             13165 non-null  int64
 9   cashier_name          13165 non-null  str
 10  tender_type           13165 non-null  str
 11  customer_segment      13165 non-null  str
 12  product_upc           13165 non-null  int64
 13  product_name          13165 non-null  str
 14  brand                 13165 non-null  str
 15  department_name       13165 non-null  str
 16  category_name         13165 non-null  str
 17  size                  13165 non-null  str
 18  unit                  13165 non-null  str
 19  vendor_name           13165 non-null  str
 20  vendor_phone          13165 non-null  str
 21  pack_size             13165 non-null  int64
 22  regular_price         13165 non-null  float64
 23  unit_cost             13165 non-null  float64
 24  quantity              13165 non-null  int64
 25  promo_type            1324 non-null   str
 26  promo_id              1324 non-null   str
 27  unit_price_effective  13165 non-null  float64
 28  line_subtotal         13165 non-null  float64
 29  tax_amount            13165 non-null  float64
 30  weekend_flag          13165 non-null  bool
 31  sale_time             13165 non-null  object
 32  sale_date             13165 non-null  object
dtypes: bool(1), datetime64[us](1), float64(5), int64(6), object(2), str(18)
memory usage: 3.2+ MB

In [197]:
q4_sales.drop("sales_time", axis = 1, inplace = True)

KeyError: "['sales_time'] not found in axis"

In [198]:
q4_sales.drop("sales_date", axis = 1, inplace = True)

KeyError: "['sales_date'] not found in axis"

In [199]:
q4_sales.isnull().sum()

receipt_id                  0
line_number                 0
sale_datetime               0
store_id                    0
store_name                  0
store_address               0
store_city                  0
store_state                 0
store_zip                   0
cashier_name                0
tender_type                 0
customer_segment            0
product_upc                 0
product_name                0
brand                       0
department_name             0
category_name               0
size                        0
unit                        0
vendor_name                 0
vendor_phone                0
pack_size                   0
regular_price               0
unit_cost                   0
quantity                    0
promo_type              11841
promo_id                11841
unit_price_effective        0
line_subtotal               0
tax_amount                  0
weekend_flag                0
sale_time                   0
sale_date                   0
dtype: int64

Loding data set of inventory snapshot

In [212]:
inventory = pd.read_csv("inventory_snapshots_2024.csv")

Loading first 5 row of the dataset

In [213]:
inventory.head()

,snapshot_date,store_id,store_name,store_address,store_city,store_state,store_zip,product_upc,product_name,department_name,on_hand_qty,unit_cost,inventory_cost_value
0,2024-01-01,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,433218196001,Rainshadow Produce Apples,Produce,35,2.31,80.85
1,2024-01-01,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,386379402654,Evergreen Farms Bananas,Produce,43,3.68,158.24
2,2024-01-01,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,161559407816,Evergreen Farms Kale,Produce,42,1.10,46.20
3,2024-01-01,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,931034131647,Rainshadow Produce Spinach,Produce,20,0.84,16.80
4,2024-01-01,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,534192832764,North Fork Organics Carrots,Produce,55,3.19,175.45

Getting information of our data set

In [214]:
inventory.info()

<class 'pandas.DataFrame'>
RangeIndex: 2160 entries, 0 to 2159
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   snapshot_date         2160 non-null   str
 1   store_id              2160 non-null   int64
 2   store_name            2160 non-null   str
 3   store_address         2160 non-null   str
 4   store_city            2160 non-null   str
 5   store_state           2160 non-null   str
 6   store_zip             2160 non-null   int64
 7   product_upc           2160 non-null   int64
 8   product_name          2160 non-null   str
 9   department_name       2160 non-null   str
 10  on_hand_qty           2160 non-null   int64
 11  unit_cost             2160 non-null   float64
 12  inventory_cost_value  2160 non-null   float64
dtypes: float64(2), int64(4), str(7)
memory usage: 219.5 KB

Now converting date dtype from string to date

In [215]:
inventory["snapshot_date"] = pd.to_datetime(inventory["snapshot_date"])

## Installing Required Libraries for SQL Data Transfer

To transfer cleaned data from Python (Pandas DataFrames) into MySQL, we installed two important libraries:

```python
pip install sqlalchemy pymysql

In [203]:
pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\Users\asus\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.0.50)
Requirement already satisfied: pymysql in c:\Users\asus\AppData\Local\Programs\Python\Python314\Lib\site-packages (1.2.0)
Requirement already satisfied: greenlet>=1 in c:\Users\asus\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sqlalchemy) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\Users\asus\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [204]:
from sqlalchemy import create_engine

## Creating Connection Between Python and MySQL

In [205]:
engine = create_engine(
    "mysql+pymysql://root:Password12%40@localhost/sales_data"
)

## Loading Products Data from Python to MySQL

In [ ]:
products = product[["product_upc",
                     "product_name",
                     "size",
                     "unit", "regular_price", "unit_cost",
                     "pack_size","department_ID", "vendor_ID", "brand_ID", "category_ID"]].drop_duplicates()

In [ ]:
products.to_sql(
    "product_data",
    con=engine,
    if_exists = "append",
    index = False
)

60

In [ ]:
department_clean = product[["department_ID",
                            "department_name"]].drop_duplicates()

In [ ]:
department_clean.to_sql(
    "department_data",
    con=engine,
    if_exists = "append",
    index = False
)

8

sending vendor data to sql

In [ ]:
vendors_data = product[["vendor_ID",
                        "vendor_name",
                        "vendor_phone"]].drop_duplicates()

In [ ]:
vendors_data.to_sql(
    "vendor_data",
    con=engine,
    if_exists = "append",
    index = False
)

9

sending category data to sql

In [ ]:
category_data = product[["category_ID",
                         "category_name"]].drop_duplicates()

In [ ]:
category_data.to_sql(
    "category_data",
    con=engine,
    if_exists = "append",
    index = False
)

60

sending barnd data to sql

In [ ]:
brand_data = product[["brand_ID","brand"]].drop_duplicates()

In [ ]:
brand_data.to_sql(
    "brand_data",
    con=engine,
    if_exists = "append",
    index = False
)

21

promotion data sending to sql

In [ ]:
promo = promotions[["promo_id", "product_upc", 
                         "promo_type", "discount_percent",
                         "start_date", "end_date"]].drop_duplicates()

In [ ]:
missing_upc = set(promotions["product_upc"]) - set(product["product_upc"])

missing_product = (
    promotions[promotions["product_upc"].isin(missing_upc)]
    [["product_upc", "product_name", "department_name", "brand"]].drop_duplicates()
)

missing_product["department_ID"] = (
    missing_product["department_name"].map(map_department)
)
missing_product["brand_ID"] = (
    missing_product["brand"].map(map_brand)
    )

missing_product.head()

,product_upc,product_name,department_name,brand,department_ID,brand_ID
0,471349361832,Meadow Meats Salmon Fillet,Meat/Seafood,Meadow Meats,7,20
1,831727889579,Sun Valley Tortillas,Grocery,Sun Valley,4,10
2,190229413186,Greenway Kitchen Tomato Soup,Deli,Greenway Kitchen,6,19
3,452991241904,Sunrise Labs Magnesium,Wellness,Sunrise Labs,5,14
4,216073375433,Sun Valley Basmati Rice,Grocery,Sun Valley,4,10

In [ ]:
missing = missing_product[["product_upc", "product_name", "department_ID",
                           "brand_ID"]].drop_duplicates()

In [ ]:
missing.to_sql(
    "product_data",
    con=engine,
    if_exists = "append",
    index = False
)

11

In [ ]:
promo.to_sql(
    "promotion_data",
    con=engine,
    if_exists = "append",
    index = False
)

530

In [ ]:
q1_sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 13545 entries, 0 to 13544
Data columns (total 33 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   receipt_id            13545 non-null  str
 1   line_number           13545 non-null  int64
 2   sale_datetime         13545 non-null  datetime64[us]
 3   store_id              13545 non-null  int64
 4   store_name            13545 non-null  str
 5   store_address         13545 non-null  str
 6   store_city            13545 non-null  str
 7   store_state           13545 non-null  str
 8   store_zip             13545 non-null  int64
 9   cashier_name          13545 non-null  str
 10  tender_type           13545 non-null  str
 11  customer_segment      13545 non-null  str
 12  product_upc           13545 non-null  int64
 13  product_name          13545 non-null  str
 14  brand                 13545 non-null  str
 15  department_name       13545 non-null  str
 16  category_name         13545 non-null  str
 17  size                  13545 non-null  str
 18  unit                  13545 non-null  str
 19  vendor_name           13545 non-null  str
 20  vendor_phone          13545 non-null  str
 21  pack_size             13545 non-null  int64
 22  regular_price         13545 non-null  float64
 23  unit_cost             13545 non-null  float64
 24  quantity              13545 non-null  int64
 25  promo_type            1299 non-null   str
 26  promo_id              1299 non-null   str
 27  unit_price_effective  13545 non-null  float64
 28  line_subtotal         13545 non-null  float64
 29  tax_amount            13545 non-null  float64
 30  weekend_flag          13545 non-null  bool
 31  sale_date             13545 non-null  object
 32  sale_time             13545 non-null  object
dtypes: bool(1), datetime64[us](1), float64(5), int64(6), object(2), str(18)
memory usage: 3.3+ MB

In [ ]:
q2_sales.info()

NameError: name 'q2_sales' is not defined

-- connecting all sales file to 1

In [206]:
sales = pd.concat(
    [q1_sales,q2_sales,q3_sales,q4_sales],
    ignore_index = True
)

In [207]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 53286 entries, 0 to 53285
Data columns (total 33 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   receipt_id            53286 non-null  str
 1   line_number           53286 non-null  int64
 2   sale_datetime         53286 non-null  datetime64[us]
 3   store_id              53286 non-null  int64
 4   store_name            53286 non-null  str
 5   store_address         53286 non-null  str
 6   store_city            53286 non-null  str
 7   store_state           53286 non-null  str
 8   store_zip             53286 non-null  int64
 9   cashier_name          53286 non-null  str
 10  tender_type           53286 non-null  str
 11  customer_segment      53286 non-null  str
 12  product_upc           53286 non-null  int64
 13  product_name          53286 non-null  str
 14  brand                 53286 non-null  str
 15  department_name       53286 non-null  str
 16  category_name         53286 non-null  str
 17  size                  53286 non-null  str
 18  unit                  53286 non-null  str
 19  vendor_name           53286 non-null  str
 20  vendor_phone          53286 non-null  str
 21  pack_size             53286 non-null  int64
 22  regular_price         53286 non-null  float64
 23  unit_cost             53286 non-null  float64
 24  quantity              53286 non-null  int64
 25  promo_type            5295 non-null   str
 26  promo_id              5295 non-null   str
 27  unit_price_effective  53286 non-null  float64
 28  line_subtotal         53286 non-null  float64
 29  tax_amount            53286 non-null  float64
 30  weekend_flag          53286 non-null  bool
 31  sale_date             53286 non-null  object
 32  sale_time             53286 non-null  object
dtypes: bool(1), datetime64[us](1), float64(5), int64(6), object(2), str(18)
memory usage: 13.1+ MB

In [ ]:
sales.head()

,receipt_id,line_number,sale_datetime,store_id,store_name,store_address,store_city,store_state,store_zip,cashier_name,...,unit_cost,quantity,promo_type,promo_id,unit_price_effective,line_subtotal,tax_amount,weekend_flag,sale_time,sale_date
0,101-20240101-0001,1,2024-01-01 14:20:00,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,Quinn,...,3.24,1,NaN,NaN,5.34,5.34,0.0,False,14:20:00,2024-01-01
1,101-20240101-0001,2,2024-01-01 14:20:00,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,Quinn,...,0.84,1,LOYALTY_PCT,PR0011647,1.09,1.09,0.0,False,14:20:00,2024-01-01
2,101-20240101-0001,3,2024-01-01 14:20:00,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,Quinn,...,3.19,2,NaN,NaN,4.52,9.04,0.0,False,14:20:00,2024-01-01
3,101-20240101-0001,4,2024-01-01 14:20:00,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,Quinn,...,0.79,2,NaN,NaN,1.09,2.18,0.0,False,14:20:00,2024-01-01
4,101-20240101-0002,1,2024-01-01 13:30:00,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,Riley,...,10.94,2,NaN,NaN,16.74,33.48,0.0,False,13:30:00,2024-01-01

In [ ]:
sales["department_ID"] = (sales["department_name"].map(map_department))

In [ ]:
sales["brand_ID"] = (sales["brand"].map(map_brand))

In [ ]:
sales = sales.merge(category_df,
                    on = "category_name",
                    how = "left"
                    )

In [ ]:
sales["vendor_ID"] = (sales["vendor_name"].map(map_vendor))

In [ ]:
product_sales = sales[["product_upc","product_name",
                       "vendor_ID", "department_ID", "category_ID", 
                       "brand_ID", "size", "pack_size",
                       "regular_price", "unit_cost","unit"]].drop_duplicates()

In [ ]:
q4_sales.head()

,receipt_id,line_number,sale_datetime,store_id,store_name,store_address,store_city,store_state,store_zip,cashier_name,...,unit_cost,quantity,promo_type,promo_id,unit_price_effective,line_subtotal,tax_amount,weekend_flag,sale_time,sale_date
0,101-20241001-0001,1,2024-10-01 12:25:00,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,Taylor,...,1.82,2,NaN,NaN,2.68,5.36,0.0,False,12:25:00,2024-10-01
1,101-20241001-0002,1,2024-10-01 12:37:00,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,Riley,...,3.76,1,NaN,NaN,5.95,5.95,0.0,False,12:37:00,2024-10-01
2,101-20241001-0002,2,2024-10-01 12:37:00,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,Riley,...,9.86,2,NaN,NaN,15.66,31.32,0.0,False,12:37:00,2024-10-01
3,101-20241001-0002,3,2024-10-01 12:37:00,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,Riley,...,0.69,1,NaN,NaN,0.92,0.92,0.0,False,12:37:00,2024-10-01
4,101-20241001-0002,4,2024-10-01 12:37:00,101,Greenway - Northside,1201 Maple Ave,Everton,WA,98111,Riley,...,3.40,1,NaN,NaN,5.47,5.47,0.0,False,12:37:00,2024-10-01

In [ ]:
product_sql = pd.read_sql(
    "select product_upc from product_data",
    con=engine
)

--compare product_upc sql and sales file

In [ ]:
new_products = product_sales[
    ~product_sales["product_upc"].isin(
        product_sql["product_upc"]
    )
]

In [ ]:
new_products.to_sql(
    "product_data",
    con=engine,
    if_exists = "append",
    index = False
)

44

- Extracted and structured store data to create a normalized store dimension table for efficient storage and integration into a SQL database.

In [ ]:
store = sales[["store_id", "store_name",
               "store_address", "store_city", "store_state",
               "store_zip"]].drop_duplicates()

In [ ]:
store.to_sql(
    "store_data",
    con=engine,
    if_exists = "append",
    index = False
)

3

In [ ]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 53286 entries, 0 to 53285
Data columns (total 33 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   receipt_id            53286 non-null  str
 1   line_number           53286 non-null  int64
 2   sale_datetime         53286 non-null  datetime64[us]
 3   store_id              53286 non-null  int64
 4   store_name            53286 non-null  str
 5   store_address         53286 non-null  str
 6   store_city            53286 non-null  str
 7   store_state           53286 non-null  str
 8   store_zip             53286 non-null  int64
 9   cashier_name          53286 non-null  str
 10  tender_type           53286 non-null  str
 11  customer_segment      53286 non-null  str
 12  product_upc           53286 non-null  int64
 13  product_name          53286 non-null  str
 14  brand                 53286 non-null  str
 15  department_name       53286 non-null  str
 16  category_name         53286 non-null  str
 17  size                  53286 non-null  str
 18  unit                  53286 non-null  str
 19  vendor_name           53286 non-null  str
 20  vendor_phone          53286 non-null  str
 21  pack_size             53286 non-null  int64
 22  regular_price         53286 non-null  float64
 23  unit_cost             53286 non-null  float64
 24  quantity              53286 non-null  int64
 25  promo_type            5295 non-null   str
 26  promo_id              5295 non-null   str
 27  unit_price_effective  53286 non-null  float64
 28  line_subtotal         53286 non-null  float64
 29  tax_amount            53286 non-null  float64
 30  weekend_flag          53286 non-null  bool
 31  sale_time             53286 non-null  object
 32  sale_date             53286 non-null  object
dtypes: bool(1), datetime64[us](1), float64(5), int64(6), object(2), str(18)
memory usage: 13.1+ MB

 Extracted and structured sales data to create a normalized store dimension table for efficient storage and integration into a SQL database.

In [208]:
sales_data = sales[["receipt_id", "sale_date", "sale_time",
                    "line_number", "quantity", "unit_price_effective",
                    "line_subtotal","tax_amount", "weekend_flag",
                    "cashier_name", "tender_type", "customer_segment",
                    "promo_id", "product_upc", "store_id"]].drop_duplicates()

In [211]:
sales_data.to_sql(
    "sales_data",
    con=engine,
    if_exists = "append",
    index = False
)

53286

--  Extracted and structured promotion data to create a normalized store dimension table for efficient storage and integration into a SQL database.

In [ ]:
promo_data = sales[["promo_id", "promo_type"]].drop_duplicates()

In [ ]:
promo_data.to_sql(
    "promotion_data",
    con=engine,
    if_exists = "append",
    index = False
)

510

In [221]:
inventory.info()

<class 'pandas.DataFrame'>
RangeIndex: 2160 entries, 0 to 2159
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   snapshot_date         2160 non-null   datetime64[us]
 1   store_id              2160 non-null   int64
 2   store_name            2160 non-null   str
 3   store_address         2160 non-null   str
 4   store_city            2160 non-null   str
 5   store_state           2160 non-null   str
 6   store_zip             2160 non-null   int64
 7   product_upc           2160 non-null   int64
 8   product_name          2160 non-null   str
 9   department_name       2160 non-null   str
 10  on_hand_qty           2160 non-null   int64
 11  unit_cost             2160 non-null   float64
 12  inventory_cost_value  2160 non-null   float64
dtypes: datetime64[us](1), float64(2), int64(4), str(6)
memory usage: 219.5 KB

In [219]:
inventory_data = inventory[["snapshot_date", "store_id", "on_hand_qty", "unit_cost", "inventory_cost_value", "product_upc"]].drop_duplicates()

In [220]:
inventory_data.to_sql(
    "inventory_data",
    con=engine,
    if_exists = "append",
    index = False
)

2160